### ISSUE TITLE
Suggestion: change prop name componentId to reactiveId

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactivebase#195]
This is an idea to be discussed as implementing can affect all working apps:

Change the componentId prop name to reactiveId instead.

The core lib philosophy is to react to changes in other components. Then using the name reactiveId fits in more naturally and is organic to explain (Component A reacts to changes in component B and component C, referenced by their reactiveIds).

Initial thoughts?

**Comment by metagrover** [comment]
I don't have a strong opinion on either. Both sound equally fine to me. How about just using `id`? As far as the justification for react prop goes - component A is subscribed to changes in component Y and Z, identified by their unique ids.

On a parallel note, component A may or may not react to changes in component B and C. For instance, you have a TextField component with `componentId="X"` with no default value and is **subscribed** to component Y and Z. Now if either one of them (Y or Z) changes, component X will get to know that the subject has changed, but it will not (can not) react to those changes since it has no value. 

Imo, Reaction is an after-effect of the subscription to the subject components. So I feel `react` prop also needs a second look 😛

**Comment by siddharthlatest** [comment]
I would argue that subscribing is an implementation detail to some extent. If we divorce how we implement this from what the library touts to do: "Build reactive user interfaces", the names react and reactiveId blend well and fit into the visual identity we are creating around reactive chemistry. Imo, they increase the recall value of the library name.

This is purely an argument from a "what sounds good to make a connection" perspective v/s a utility value in changing the name.

**Comment by divyanshu013** [comment]
First impressions, `componentId` is quite self-explanatory (since people using react or any other modern framework/library already think about the UI in terms of components), however `reactiveId` does fit in well with the **reactive** libraries.

I think it would be a trade-off between having a more self-explanatory name and creating a unique identity. If we decide to go for `reactiveId`, we could change the `react` prop to `reactTo` to make it a bit self-explanatory. For example,

> Each component accepts a unique `reactiveId` which can be then passed to any other component via a `reactTo` prop to make it react to any changes

**Comment by siddharthlatest** [comment]
Leaving this out for now.
