### ISSUE TITLE
Date components query behavior

### ISSUE THREAD

**Issue by metagrover** [appbaseio/reactivebase#99]
All date-based components should parse the date into `milli seconds` format, since `epoch_millis` are supported by default in ElasticSearch.

**Comment by farhan687** [comment]
Fixed here: 5150baeb80271ea18103a77c9932cfd3af9ba2b4

**Comment by siddharthlatest** [comment]
When making range queries with milliseconds time format, the results don't return correctly. We need to investigate how Elasticsearch behaves with different date formats before coming back here.

**Comment by siddharthlatest** [comment]
**Update**: A `queryFormat` prop will be used to specify the date format. (Applicable to both **DateRange** and **DatePicker** components)

The prop will accept the following values:

1. "epoch_millis" dates queried in milliseconds format since epoch. Also the default value.  
2. "epoch_seconds" queries the dates in seconds format since epoch.
3. "date" queries the date field using a yyyy-MM-dd format.
4. "date_time" queries the dates using a combination of date and time separated by **T**: yyyy-MM-dd'T'HH:mm:ss.SSSZZ format.
5. "date_time_no_millis" queries the dates using a combination of date and time without milliseconds separated by **T**: yyyy-MM-dd'T'HH:mm:ssZZ format.
3. "basic_date" queries the dates using a date format yyyyMMdd.
4. "basic_date_time" queries the dates using a combination of date and time yyyyMMdd'T'HHmmss.SSSZ format.
5. "basic_date_time_no_millis" queries the dates using a combination of date and time without milliseconds yyyyMMdd'T'HHmmssZ format.
6. "basic_time" queries the date field using just time in the HHmmss.SSZ format.
7. "basic_time_no_millis" queries the date field using just time without milliseconds in a HHmmss format.

These are a subset of the date formats supported by Elasticsearch and their format definitions can be referenced here - https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html#built-in-date-formats.

**Comment by farhan687** [comment]
Fixed here: 6a2a48649da8b45a81a4bd1eb4c798ab99d4d583
